#ifndef _CTS_COMMON_DEFINE_H_
#define _CTS_COMMON_DEFINE_H_


//GENERIC ===========================================================================================
#define CTS_COM_DISABLE								0
#define CTS_COM_ENABLE								1


//CONFIG ===========================================================================================
#define CTS_COM_ACCESS_DENIED						0
#define CTS_COM_READ_ONLY							1
#define CTS_COM_READ_AND_WRITE						2
#define CTS_COM_ADMINISTRATOR						3
#define CTS_COM_HOMEUSER							11 //Jamie@CTS:20160829 FWR/VRG
#define CTS_COM_TEST_SUPPORT						5
#define CTS_COM_TECHNICAL_SUPPORT					9
#define CTS_COM_FACTORY_SUPPORT						(-1)

#define CTS_COM_LOGIN_TYPE_CONSOLE					0
#define CTS_COM_LOGIN_TYPE_SNMP						1
#define CTS_COM_LOGIN_TYPE_WEB						2

#define CTS_COM_SOCKET_TYPE_TELNET					1
#define CTS_COM_SOCKET_TYPE_SSH						2

#define CTS_COM_MAX_TELNET_SESSION_NUM				4
#define CTS_COM_MAX_DNS_SERVER_NUM					2
#define CTS_COM_MAX_NTP_SERVER_NUM					2
#define CTS_COM_MAX_TIMEZONE_ITEM_NUM				136			/* total number of time zone entries(0~135) */
#define CTS_COM_MAX_EVENT_LOG_NUM					500
#define CTS_COM_MAX_MIRROR_VID_NUM					8
#define CTS_COM_MAX_MIRROR_IP_NUM					8
#define CTS_COM_MAX_REMARKING_PRIORITY_NUM			8

#define CTS_COM_MAX_MAC_TABLE_NUM					2048
#define CTS_COM_MAX_MAC_FORWARD_FILTER_NUM			128
#define CTS_COM_MIN_PORT_TRUNK_GROUP_NUM			2
#define CTS_COM_MAX_PORT_TRUNK_GROUP_NUM			8
#define CTS_COM_MAX_RADIUS_SERVER_IP_NUM			2
#define CTS_COM_MAX_STATIC_IP_GROUP_NUM				48
#define CTS_COM_MAX_DHCP_SNOOPING_STATE_NUM			448
#define CTS_COM_MAX_DHCPV6_SNOOPING_STATE_NUM		512
#define CTS_COM_MAX_SOURCE_BINDING_NUM				12
#define CTS_COM_MAX_IPMULTICAST_IDX_NUM				128
#define CTS_COM_MAX_IPMC_NAME_STRING_LEN			24
#define CTS_COM_MAX_IPMC_SEGMENT_NUM				400
#define CTS_COM_MAX_IPMC_PROFILE_NUM				60
#define CTS_COM_MAX_IPMC_PROFILE_SEGMENTID_NUM		400
#define CTS_COM_MAX_IPMC_PROFILE_SEGMENTID_IDX		10
#define CTS_COM_MAX_IGMP_FILTER_NUM					CTS_COM_MAX_PORT_NUM
#define CTS_COM_MAX_IGMP_FILTER_CHANNEL_LIMIT_NUM	512

#define CTS_COM_MIN_DSCP_PRIORITY					0
#define CTS_COM_MAX_DSCP_PRIORITY					63
#define CTS_COM_MIN_8021P_PRIORITY					0
#define CTS_COM_MAX_8021P_PRIORITY					7


#define CTS_COM_UTC_D20030918						1063853552UL


//ERROR ===========================================================================================
#define CTS_COM_ERR_TYPE_ERROR						1000
#define CTS_COM_ERR_BOOT_FAILED						1001
#define CTS_COM_ERR_LOAD_CONFIG_FAILED				1002
#define CTS_COM_ERR_LOAD_DEFAULT_CONFIG_FAILED		1003
#define CTS_COM_ERR_SAVE_CONFIG_FAILED				1004
#define CTS_COM_ERR_SAVE_DEFAULT_CONFIG_FAILED		1005

//WARNING =========================================================================================
#define CTS_COM_WARN_TYPE_WARNING					2000
#define CTS_COM_WARN_LOGIN_FAILED					2001
#define CTS_COM_WARN_LOCAL_MODULE_DOWN				2002
#define CTS_COM_WARN_REMOTE_POWER_DOWN				2003
#define CTS_COM_WARN_POWER_MODULE_DOWN				2004
#define CTS_COM_WARN_POWER_FAN_FAILED				2005
#define CTS_COM_WARN_AUTO_BACKUP_FAILED				2006
#define CTS_COM_WARN_AUTO_UPDATE_FAILED				2007
#define CTS_COM_WARN_CASE_FAN_FAILED				2008
#define CTS_COM_WARN_SFP_TEMPERATURE_FAILED			2009
#define CTS_COM_WARN_SFP_VOLTAGE_FAILED				2010
#define CTS_COM_WARN_SFP_TXBIAS_FAILED				2011
#define CTS_COM_WARN_LOOP_DETECTION					2012
#define CTS_COM_WARN_UPDATE_FAILED					2013
#define CTS_COM_WARN_DHCP_SNOOPING					2014
#define CTS_COM_WARN_DIGITAL_INPUT					2015
#define CTS_COM_WARN_DIGITAL_OUTPUT					2016
#define CTS_COM_WARN_REMOTE_FIBER_DOWN				2017
#define CTS_COM_WARN_TEMP_OVERHEAT					2018
#define CTS_COM_WARN_POWER_SUPPLY_NO				2019
#define CTS_COM_WARN_MODULE_UPDATE					2020
#define CTS_COM_WARN_POWER_MODULE_MISSING			2021
#define CTS_COM_WARN_POE_SYSTEM_POWER_OVER			2022
#define CTS_COM_WARN_POE_PORT_POWER_OVER			2023
#define CTS_COM_WARN_CPU_OVER_LOADING				2024

//INFORMATION =======================================================================================
#define CTS_COM_INFO_TYPE_INFO						3000
#define CTS_COM_INFO_COLD_START						3001
#define CTS_COM_INFO_WARM_START						3002
#define CTS_COM_INFO_LOGIN							3003
#define CTS_COM_INFO_LOGOUT							3004
#define CTS_COM_INFO_TIMEOUT						3005
#define CTS_COM_INFO_DISCONNECTED					3006
#define CTS_COM_INFO_LINK_UP						3007
#define CTS_COM_INFO_LINK_DOWN						3008
#define CTS_COM_INFO_LOCAL_MODULE_UP				3009
#define CTS_COM_INFO_REMOTE_POWER_UP				3010
#define CTS_COM_INFO_POWER_MODULE_UP				3011
#define CTS_COM_INFO_POWER_FAN_OK					3012
#define CTS_COM_INFO_LINK_PASS						3018
#define CTS_COM_INFO_LINK_OFF						3019
#define CTS_COM_INFO_AUTO_BACKUP_SUCCEEDED			3020
#define CTS_COM_INFO_AUTO_UPDATE_SUCCEEDED			3021
#define CTS_COM_INFO_CASE_FAN_OK					3022
#define CTS_COM_INFO_SFP_TEMPERATURE_OK				3023
#define CTS_COM_INFO_SFP_VOLTAGE_OK					3024
#define CTS_COM_INFO_SFP_TXBIAS_OK					3025
#define CTS_COM_INFO_DIGITAL_INPUT					3026
#define CTS_COM_INFO_DIGITAL_OUTPUT					3027
#define CTS_COM_INFO_TEMP_NORMAL					3028
#define CTS_COM_INFO_POWER_SUPPLY_YES				3029
#define CTS_COM_INFO_FEF_YES						3030
#define CTS_COM_INFO_FEF_NO							3031
#define CTS_COM_INFO_SD_YES							3032
#define CTS_COM_INFO_SD_NO							3033
#define CTS_COM_INFO_MODULE_UPDATE	         		3034
#define CTS_COM_INFO_PROTOCOL_SYNC	         		3035
#define CTS_COM_INFO_LOSS_SYNC		         		3036
#define CTS_COM_INFO_CONFIG_CHANGE	         		3037



#define CTS_COM_SOURCE_LOCAL_MACHINE				4000
#define CTS_COM_SOURCE_RS232D						4001
#define CTS_COM_SOURCE_RS232						4002
#define CTS_COM_SOURCE_TELNETD						4003
#define CTS_COM_SOURCE_TELNET						4004
#define CTS_COM_SOURCE_TFTPD						4005
#define CTS_COM_SOURCE_TFTP							4006
#define CTS_COM_SOURCE_FTPD							4007
#define CTS_COM_SOURCE_FTP							4008
#define CTS_COM_SOURCE_SNMPD						4009
#define CTS_COM_SOURCE_SNMP							4010
#define CTS_COM_SOURCE_WEBD							4011
#define CTS_COM_SOURCE_WEB							4012
#define CTS_COM_SOURCE_PING							4013
#define CTS_COM_SOURCE_WATCH_DOG					4014
#define CTS_COM_SOURCE_REMOTE_MACHINE				4015
#define CTS_COM_SOURCE_CATV_MODULE					4016
#define CTS_COM_SOURCE_RSTP							4017
#define CTS_COM_SOURCE_LACP							4018
#define CTS_COM_SOURCE_PORT_TRUNK					4019


#define CTS_COM_CAT_PORT0							5001
#define CTS_COM_CAT_PORT1							5002
#define CTS_COM_CAT_PORT_COPPER						5003
#define CTS_COM_CAT_PORT_FIBER						5004
#define CTS_COM_CAT_POWER_MODULE_A					5005
#define CTS_COM_CAT_POWER_MODULE_A_FAN1				5006
#define CTS_COM_CAT_POWER_MODULE_A_FAN2				5007
#define CTS_COM_CAT_POWER_MODULE_B					5008
#define CTS_COM_CAT_POWER_MODULE_B_FAN1				5009
#define CTS_COM_CAT_POWER_MODULE_B_FAN2				5010
#define CTS_COM_CAT_PORT2							5011
#define CTS_COM_CAT_PORT3							5012
#define CTS_COM_CAT_PORT_AD_COPPER					5013
#define CTS_COM_CAT_PORT_AD_FIBER					5014
#define CTS_COM_CAT_CASE_FAN1						5015
#define CTS_COM_CAT_CASE_FAN2						5016
#define CTS_COM_CAT_CASE_FAN3						5017
#define CTS_COM_CAT_LOOP_DETECTION					5018
#define CTS_COM_CAT_AUTO_UPDATE						5019
#define CTS_COM_CAT_UPDATE							5020
#define CTS_COM_CAT_CASE_FAN						5021
#define CTS_COM_CAT_DHCP_SNOOPING					5022
#define CTS_COM_CAT_DIGITAL_INPUT					5023
#define CTS_COM_CAT_EVENT_DIGITAL_INPUT1			5024
#define CTS_COM_CAT_EVENT_DIGITAL_INPUT2			5025
#define CTS_COM_CAT_EVENT_POWER1					5026
#define CTS_COM_CAT_EVENT_POWER2					5027
#define CTS_COM_CAT_EVENT_PORT						5028
#define CTS_COM_CAT_CPU_OVER_LOADING				5029

#define CTS_COM_CAT_PORT0_COPPER					5029
#define CTS_COM_CAT_PORT1_COPPER					5030
#define CTS_COM_CAT_PORT2_COPPER					5031
#define CTS_COM_CAT_PORT3_COPPER					5032
#define CTS_COM_CAT_PORT0_FIBER						5033
#define CTS_COM_CAT_PORT1_FIBER						5034
#define CTS_COM_CAT_PORT2_FIBER						5035
#define CTS_COM_CAT_PORT3_FIBER						5036
#define CTS_COM_CAT_PORT_FIBER_MM					5037
#define CTS_COM_CAT_PORT_FIBER_SM					5038
#define CTS_COM_CAT_PORT_FIBER_SLAVE				5039
#define CTS_COM_CAT_PORT_FIBER_MASTER				5040

#define CTS_COM_CAT_MODULE_PORT_COPPER				5041
#define CTS_COM_CAT_MODULE_PORT_FIBER				5042
#define CTS_COM_CAT_MODULE_UPDATE   				5043

#define CTS_COM_CAT_POWER_MODULE_1					5045
#define CTS_COM_CAT_POWER_MODULE_2					5046

#define CTS_COM_CAT_EVENT_POWER_A					5047
#define CTS_COM_CAT_EVENT_POWER_B					5048
#define CTS_COM_CAT_EVENT_SLOT						5049
#define CTS_COM_CAT_EVENT_SLOT_PORT					5050
#define CTS_COM_CAT_EVENT_LAN_PORT					5051

#define CTS_COM_CAT_POE_THRESHOLD					5052
#define CTS_COM_CAT_POE_PORT_BUDGET					5053

#define CTS_COM_CAT_PROTOCOL_LINK_UP				5054
#define CTS_COM_CAT_PROTOCOL_LINK_DOWN				5055
#define CTS_COM_CAT_PROTOCOL_SYNC					5056
#define CTS_COM_CAT_PROTOCOL_LOST_SYNC				5057
#define CTS_COM_CAT_PROTOCOL_CFG_CHANGE				5058


//Company INFO ============================================================================================
#define CTS_COM_COMPANY_CTS							0x0
#define CTS_COM_COMPANY_GB							0x1
#define CTS_COM_COMPANY_PCT							0x2
#define CTS_COM_COMPANY_MICROSENS					0x3
#define CTS_COM_COMPANY_OCOM						0x4
#define CTS_COM_COMPANY_CUBE						0x5
#define CTS_COM_COMPANY_SIGNAMAX					0x6
#define CTS_COM_COMPANY_DASANSMC					0x7
//¥@ÅA»·¶Ç											0x8
#define CTS_COM_COMPANY_EDIMAX						0x9
#define CTS_COM_COMPANY_QEES						0xA
#define CTS_COM_COMPANY_ACT							0xB
#define CTS_COM_COMPANY_VN							0xC
#define CTS_COM_COMPANY_BEAM						0xD
#define CTS_COM_COMPANY_DASANNETWORKS				0xE
#define CTS_COM_COMPANY_LANTECH						0xF
#define CTS_COM_COMPANY_C4							0x10
#define CTS_COM_COMPANY_KOPPARSTADEN				0x11
#define CTS_COM_COMPANY_TELIASONERA					0x12
#define CTS_COM_COMPANY_ACT_FOS						0x13
#define CTS_COM_COMPANY_BEAM_FOS					0x14
#define CTS_COM_COMPANY_SONGCONG_VT					0x15
#define CTS_COM_COMPANY_SONGCONG_VN					0x16
#define CTS_COM_COMPANY_ASCENTEK					0x17
#define CTS_COM_COMPANY_TELRAN						0x18
#define CTS_COM_COMPANY_TECHAYA						0x19
#define CTS_COM_COMPANY_SWISSCOM					0x1A
#define CTS_COM_COMPANY_SONGCONG_VT15				0x1B
#define CTS_COM_COMPANY_CTS_NE_DAIMLER				0x1C
#define CTS_COM_COMPANY_CTS_NE_HALMSTAD				0x1D
#define CTS_COM_COMPANY_JPN_FTTH					0x1E
#define CTS_COM_COMPANY_ICONNECTRON					0x1F
#define CTS_COM_COMPANY_ACT_AFX24D					0x20
#define CTS_COM_COMPANY_BEAM_AFX24D					0x21
#define CTS_COM_COMPANY_AZURETEC					0x22
#define CTS_COM_COMPANY_ISON						0x23
#define CTS_COM_COMPANY_MERTELSYSTEM_CAT			0x24
#define CTS_COM_COMPANY_CASACOM						0x25


// Product ID ============================================================================================
#define CTS_COM_PRODUCT_ID_NONE						0
#define CTS_COM_PRODUCT_ID_HES_3109					0x28
#define CTS_COM_PRODUCT_ID_HES_3106					0x2B
#define CTS_COM_PRODUCT_ID_HES_3106P				0x2C
#define CTS_COM_PRODUCT_ID_HES_3112					0x2D
#define CTS_COM_PRODUCT_ID_HES_3109C				0x2F

#define CTS_COM_PRODUCT_ID_HPS_3106					0x36
#define CTS_COM_PRODUCT_ID_IES_3106					0x37
#define CTS_COM_PRODUCT_ID_ICPE						0x38
#define CTS_COM_PRODUCT_ID_IPS_3110					0x39
#define CTS_COM_PRODUCT_ID_IPS_3106P				0x3A
#define CTS_COM_PRODUCT_ID_IPS_3112					0x3B

#define CTS_COM_PRODUCT_ID_FOS_3148					0xA3
#define CTS_COM_PRODUCT_ID_FOS_3128					0xA4
#define CTS_COM_PRODUCT_ID_FOS_3124					0xA5
#define CTS_COM_PRODUCT_ID_ESW_3128					0xA6
#define CTS_COM_PRODUCT_ID_FOS_5126					0xA7
#define CTS_COM_PRODUCT_ID_EPS_3128					0xA8

#define CTS_COM_PRODUCT_ID_MCT_100					0x61
#define CTS_COM_PRODUCT_ID_MCT_3002					0x62
#define CTS_COM_PRODUCT_ID_MCT_RACK					0x63
#define CTS_COM_PRODUCT_ID_MCT_2612					0x65
#define CTS_COM_PRODUCT_ID_MCT_3612					0x66
#define CTS_COM_PRODUCT_ID_MCT_3512					0x67
#define CTS_COM_PRODUCT_ID_MCT_RACK12				0x68

#define CTS_COM_PRODUCT_ID_SMS_3109					0x72
#define CTS_COM_PRODUCT_ID_SMS_3109C				0x73

#define CTS_COM_PRODUCT_ID_VRG5						0xDD

#define CTS_COM_PRODUCT_ID_FWR5						0xFD

// Hardware ID ============================================================================================
#define CTS_COM_HARDWARE_BASE						5000
#define CTS_COM_HW_ID_FOS_3126						(CTS_COM_HARDWARE_BASE+1)
#define CTS_COM_HW_ID_FOS_4126						(CTS_COM_HARDWARE_BASE+2)
#define CTS_COM_HW_ID_MCT_3112						(CTS_COM_HARDWARE_BASE+3)
#define CTS_COM_HW_ID_MCT_2114						(CTS_COM_HARDWARE_BASE+4)
#define CTS_COM_HW_ID_CCT_CHASSIS2					(CTS_COM_HARDWARE_BASE+5)
#define CTS_COM_HW_ID_SWH_2109						(CTS_COM_HARDWARE_BASE+6)
#define CTS_COM_HW_ID_CCT_CHASSIS3					(CTS_COM_HARDWARE_BASE+7)
#define CTS_COM_HW_ID_VRG_21412						(CTS_COM_HARDWARE_BASE+8)
#define CTS_COM_HW_ID_SWH_3114						(CTS_COM_HARDWARE_BASE+9)
#define CTS_COM_HW_ID_FOS_3126P						(CTS_COM_HARDWARE_BASE+10)
#define CTS_COM_HW_ID_ESH_3105						(CTS_COM_HARDWARE_BASE+11)
#define CTS_COM_HW_ID_VRG_31612						(CTS_COM_HARDWARE_BASE+12)
#define CTS_COM_HW_ID_SWH_3124						(CTS_COM_HARDWARE_BASE+13)
#define CTS_COM_HW_ID_ESH_3605						(CTS_COM_HARDWARE_BASE+14)
#define CTS_COM_HW_ID_ESH_2106						(CTS_COM_HARDWARE_BASE+15)
#define CTS_COM_HW_ID_SWH_2126						(CTS_COM_HARDWARE_BASE+16)
#define CTS_COM_HW_ID_ESW_2128						(CTS_COM_HARDWARE_BASE+17)
#define CTS_COM_HW_ID_FOS_2128						(CTS_COM_HARDWARE_BASE+18)
#define CTS_COM_HW_ID_HET_2106						(CTS_COM_HARDWARE_BASE+20)
#define CTS_COM_HW_ID_HET_3105A						(CTS_COM_HARDWARE_BASE+21)
#define CTS_COM_HW_ID_HET_3105B						(CTS_COM_HARDWARE_BASE+22)
#define CTS_COM_HW_ID_HES_2109						(CTS_COM_HARDWARE_BASE+23)
#define CTS_COM_HW_ID_HES_3109						(CTS_COM_HARDWARE_BASE+24)
#define CTS_COM_HW_ID_HES_3106						(CTS_COM_HARDWARE_BASE+25)
#define CTS_COM_HW_ID_HES_3106P						(CTS_COM_HARDWARE_BASE+26)
#define CTS_COM_HW_ID_HES_3112						(CTS_COM_HARDWARE_BASE+27)
#define CTS_COM_HW_ID_HPS_3113						(CTS_COM_HARDWARE_BASE+28)
#define CTS_COM_HW_ID_HES_IMC						(CTS_COM_HARDWARE_BASE+29)
#define CTS_COM_HW_ID_FOS_3124						(CTS_COM_HARDWARE_BASE+30)
#define CTS_COM_HW_ID_FOS_3148						(CTS_COM_HARDWARE_BASE+31)
#define CTS_COM_HW_ID_FOS_3128						(CTS_COM_HARDWARE_BASE+32)
#define CTS_COM_HW_ID_FOS_3124R						(CTS_COM_HARDWARE_BASE+33)
#define CTS_COM_HW_ID_ESW_3128						(CTS_COM_HARDWARE_BASE+34)
#define CTS_COM_HW_ID_FOS_5126						(CTS_COM_HARDWARE_BASE+35)
#define CTS_COM_HW_ID_EPS_3128						(CTS_COM_HARDWARE_BASE+36)
#define CTS_COM_HW_ID_IES_3106						(CTS_COM_HARDWARE_BASE+40)
#define CTS_COM_HW_ID_HES_3109C						(CTS_COM_HARDWARE_BASE+41)
#define CTS_COM_HW_ID_ICPE							(CTS_COM_HARDWARE_BASE+42)
#define CTS_COM_HW_ID_MCT_RACK						(CTS_COM_HARDWARE_BASE+43)
#define CTS_COM_HW_ID_MCT_RACK12					(CTS_COM_HARDWARE_BASE+44)
#define CTS_COM_HW_ID_IPS_3110						(CTS_COM_HARDWARE_BASE+45)
#define CTS_COM_HW_ID_IPS_3106P						(CTS_COM_HARDWARE_BASE+46)
#define CTS_COM_HW_ID_HPS_3106						(CTS_COM_HARDWARE_BASE+47)
#define CTS_COM_HW_ID_IPS_3112						(CTS_COM_HARDWARE_BASE+48)

//===================
#define CTS_COM_HW_ID_VRG5							(CTS_COM_HARDWARE_BASE+1000)
#define CTS_COM_HW_ID_FWR5							(CTS_COM_HARDWARE_BASE+1001)

#define CTS_COM_STRUCTURE_VERSION					6000


// Generic ============================================================================================
#include "cts_board_config.h"
#define CTS_COM_VID_MIN								1
#define CTS_COM_VID_MAX								4094
#define CTS_COM_PORT_IS_VALID( port )				( (port) >= 0 && (port) < CTS_COM_MAX_PORT_NUM )
#define CTS_COM_UNITID_IS_VALID( unitid )			( (unitid) >= 0 && (unitid) < CTS_COM_MAX_SLOT_NUM )
#define CTS_COM_VID_IS_VALID( vid )					( (vid) >= CTS_COM_VID_MIN && (vid) <= CTS_COM_VID_MAX )
#define CTS_COM_PRI_IS_VALID( pri )					( (pri) >= 0 && (pri) <= 7 )
#define CTS_COM_QUEUE_IS_VALID( q )					( (q) >= 0 && (q) < CTS_COM_MAX_QUEUE_NUM )
#define CTS_COM_PORTBMP_SIZE						( (CTS_COM_MAX_PORT_NUM+7)>>3 )
#define CTS_COM_VLAN_PORT_IS_VALID( port )			( (port) >= 0 && (port) < CTS_COM_MAX_VLAN_PORT_NUM )
#define CTS_COM_VLAN_PORTBMP_SIZE					( (CTS_COM_MAX_VLAN_PORT_NUM+7)>>3 )
#define CTS_COM_VIDBMP_SIZE							( 4096>>3 )
#define CTS_COM_DFT_MGMT_VID						1
#define CTS_COM_MAX_VLAN_STRING_BUF_LENGTH			(1 + CTS_COM_VID_MAX * 6)
#define CTS_COM_SLOTBMP_SIZE						( (CTS_COM_MAX_SLOT_NUM+7)>>3 )

#undef XMK_STR
#undef MK_STR
#define XMK_STR(x)	#x
#define MK_STR(x)	XMK_STR(x)

#define CTS_COM_MAX_PORT_NUM_STR					MK_STR(CTS_COM_MAX_PORT_NUM)
#define CTS_COM_MAX_PORT_NUM_INCL_CPU_STR			MK_STR(CTS_COM_MAX_PORT_NUM_INCL_CPU)

#include "cts_common_define_vlan.h"
//#include "cts_acl_config.h"

#endif /* _CTS_COMMON_DEFINE_H_ */
